schema_version = "1.0.0"


id = "mengges_dark_theme"
version = "1.2.0"
name = "MengGe's Dark Theme"
tagline = "Dark Theme Pro Max Ultra Plus Lift"
maintainer = "MengGe_KKD <https://menggekkd.me>"

type = "theme"

tags = ["Dark"]

blender_version_min = "5.0.0"

license = [
  "SPDX:GPL-2.0-or-later",
]
